#!/bin/bash

SSH_PIPE_FILE="/tmp/ssh_with_pipe"

set -- "${1:-$(cat -)}" "${@:2}"

copy "$@" &

to_copy="${*//$'\n'/NEWLINE_FOR_COPY}" # Escape newlines in input.
echo "copy $to_copy" >> "$SSH_PIPE_FILE"
